import { comment } from "../models";



export const commentsDB:comment[] = [
    {
        id: 1,
        fkProduct: 1,
        byName: "María Gómez",
        byEmail: "maria.gomez@example.com",
        text: "Muy cómodo y perfecto para entrenar sin molestias.",
        date: "2025-01-19T16:52:30.123Z",
      },
      {
        id: 2,
        fkProduct: 1,
        byName: "Carlos Pérez",
        byEmail: "carlos.perez@example.com",
        text: "Me encanta, ideal para mis sesiones en el gimnasio.",
        date: "2025-01-19T16:53:45.456Z",
      },
      {
        id: 3,
        fkProduct: 2,
        byName: "Laura Fernández",
        byEmail: "laura.fernandez@example.com",
        text: "Este polo es excelente para el uso diario, muy suave.",
        date: "2025-01-19T16:55:12.789Z",
      },
      {
        id: 4,
        fkProduct: 3,
        byName: "Juan Rodríguez",
        byEmail: "juan.rodriguez@example.com",
        text: "Ligero y fresco, ideal para el verano.",
        date: "2025-01-19T16:56:30.234Z",
      },
      {
        id: 5,
        fkProduct: 3,
        byName: "Ana Martínez",
        byEmail: "ana.martinez@example.com",
        text: "Muy cómodo, perfecto para los días más calurosos.",
        date: "2025-01-19T16:58:15.567Z",
      },
      {
        id: 6,
        fkProduct: 4,
        byName: "Pedro Ramírez",
        byEmail: "pedro.ramirez@example.com",
        text: "Un básico imprescindible, lo uso para cualquier ocasión.",
        date: "2025-01-19T16:59:48.890Z",
      },
      {
        id: 7,
        fkProduct: 5,
        byName: "Lucía Torres",
        byEmail: "lucia.torres@example.com",
        text: "Me encanta el estampado, es muy moderno.",
        date: "2025-01-19T17:01:05.123Z",
      },
      {
        id: 8,
        fkProduct: 6,
        byName: "Andrés García",
        byEmail: "andres.garcia@example.com",
        text: "Es perfecto para los días soleados, muy ligero.",
        date: "2025-01-19T17:02:45.456Z",
      },
      {
        id: 9,
        fkProduct: 6,
        byName: "Sofía López",
        byEmail: "sofia.lopez@example.com",
        text: "Ligero y cómodo, me encantó para el verano.",
        date: "2025-01-19T17:04:30.789Z",
      },
      {
        id: 10,
        fkProduct: 7,
        byName: "Elena López",
        byEmail: "elena.lopez@example.com",
        text: "Perfecto para el clima frío, muy cálido y elegante.",
        date: "2025-01-19T17:05:30.123Z",
      },
      {
        id: 11,
        fkProduct: 7,
        byName: "Ricardo Martínez",
        byEmail: "ricardo.martinez@example.com",
        text: "Excelente abrigo, lo uso todo el tiempo en invierno.",
        date: "2025-01-19T17:06:45.456Z",
      },
      {
        id: 12,
        fkProduct: 8,
        byName: "Paula Sánchez",
        byEmail: "paula.sanchez@example.com",
        text: "Muy abrigado, ideal para los días más fríos del invierno.",
        date: "2025-01-19T17:07:30.789Z",
      },
      {
        id: 13,
        fkProduct: 8,
        byName: "Luis Gómez",
        byEmail: "luis.gomez@example.com",
        text: "Me encanta el forro polar, mantiene el calor todo el día.",
        date: "2025-01-19T17:08:12.234Z",
      },
      {
        id: 14,
        fkProduct: 9,
        byName: "Marta Rodríguez",
        byEmail: "marta.rodriguez@example.com",
        text: "Un abrigo elegante y muy moderno, perfecto para ocasiones especiales.",
        date: "2025-01-19T17:09:05.567Z",
      },
      {
        id: 15,
        fkProduct: 9,
        byName: "Javier Pérez",
        byEmail: "javier.perez@example.com",
        text: "De excelente calidad y con un diseño único, lo recomiendo.",
        date: "2025-01-19T17:10:15.890Z",
      },
      {
        id: 16,
        fkProduct: 10,
        byName: "Isabel Fernández",
        byEmail: "isabel.fernandez@example.com",
        text: "Perfecto para el otoño, se siente suave y cómodo.",
        date: "2025-01-19T17:11:40.123Z",
      },
      {
        id: 17,
        fkProduct: 10,
        byName: "Alejandro Ruiz",
        byEmail: "alejandro.ruiz@example.com",
        text: "Muy buen abrigo de cuero, combina con todo, me encanta.",
        date: "2025-01-19T17:12:55.456Z",
      },
      {
        id: 18,
        fkProduct: 11,
        byName: "Cristina Díaz",
        byEmail: "cristina.diaz@example.com",
        text: "Un abrigo muy cálido y liviano, ideal para los días fríos.",
        date: "2025-01-19T17:13:50.789Z",
      },
      {
        id: 19,
        fkProduct: 11,
        byName: "Fernando Jiménez",
        byEmail: "fernando.jimenez@example.com",
        text: "Increíblemente ligero pero muy efectivo para el frío.",
        date: "2025-01-19T17:15:15.123Z",
      },
      {
        id: 20,
        fkProduct: 12,
        byName: "Valeria Torres",
        byEmail: "valeria.torres@example.com",
        text: "Me encanta el estilo oversize, perfecto para el invierno.",
        date: "2025-01-19T17:16:10.456Z",
      },
      {
        id: 21,
        fkProduct: 12,
        byName: "Carlos Martínez",
        byEmail: "carlos.martinez@example.com",
        text: "Cómodo y con mucho estilo, lo uso para cualquier ocasión.",
        date: "2025-01-19T17:17:05.789Z",
      },
      {
        id: 22,
        fkProduct: 13,
        byName: "Ana Gómez",
        byEmail: "ana.gomez@example.com",
        text: "Una cartera muy bonita y elegante, ideal para resaltar cualquier look.",
        date: "2025-01-19T17:18:00.123Z",
      },
      {
        id: 23,
        fkProduct: 13,
        byName: "Luis García",
        byEmail: "luis.garcia@example.com",
        text: "Me encanta la estética de la cartera, es justo lo que buscaba para mi estilo.",
        date: "2025-01-19T17:19:10.456Z",
      },
      {
        id: 24,
        fkProduct: 14,
        byName: "Carla Torres",
        byEmail: "carla.torres@example.com",
        text: "Una cartera sofisticada y perfecta para ocasiones elegantes.",
        date: "2025-01-19T17:20:15.789Z",
      },
      {
        id: 25,
        fkProduct: 14,
        byName: "Ricardo Ruiz",
        byEmail: "ricardo.ruiz@example.com",
        text: "La calidad es impresionante, la cartera tiene un acabado excelente.",
        date: "2025-01-19T17:21:05.123Z",
      },
      {
        id: 26,
        fkProduct: 15,
        byName: "Elena Martínez",
        byEmail: "elena.martinez@example.com",
        text: "Este collar es precioso, el diseño de corazón es muy delicado.",
        date: "2025-01-19T17:22:10.456Z",
      },
      {
        id: 27,
        fkProduct: 15,
        byName: "José López",
        byEmail: "jose.lopez@example.com",
        text: "Me encanta cómo brilla el collar, realmente parece de alta gama.",
        date: "2025-01-19T17:23:15.789Z",
      },
      {
        id: 28,
        fkProduct: 16,
        byName: "Patricia Sánchez",
        byEmail: "patricia.sanchez@example.com",
        text: "La bufanda es súper suave y muy calentita, perfecta para el invierno.",
        date: "2025-01-19T17:24:05.123Z",
      },
      {
        id: 29,
        fkProduct: 16,
        byName: "Carlos Pérez",
        byEmail: "carlos.perez@example.com",
        text: "Excelente calidad, me protege mucho del frío y se ve muy bien.",
        date: "2025-01-19T17:25:20.456Z",
      },
      {
        id: 30,
        fkProduct: 17,
        byName: "Lucía Fernández",
        byEmail: "lucia.fernandez@example.com",
        text: "El sombrero es perfecto para los días de verano, cómodo y ligero.",
        date: "2025-01-19T17:26:00.789Z",
      },
      {
        id: 31,
        fkProduct: 17,
        byName: "Juan Rodríguez",
        byEmail: "juan.rodriguez@example.com",
        text: "Muy fresco para el verano, me lo llevo siempre a la playa.",
        date: "2025-01-19T17:27:10.123Z",
      },
      {
        id: 32,
        fkProduct: 18,
        byName: "Isabel Gómez",
        byEmail: "isabel.gomez@example.com",
        text: "Los guantes son muy cómodos y protegen del frío sin perder sensibilidad.",
        date: "2025-01-19T17:28:00.456Z",
      },
      {
        id: 33,
        fkProduct: 18,
        byName: "Antonio Martínez",
        byEmail: "antonio.martinez@example.com",
        text: "El cuero de estos guantes es de muy buena calidad y se sienten muy suaves.",
        date: "2025-01-19T17:29:05.789Z",
      },
]