import { comment } from "../models";



export const commentsDB:comment[] = [
    {
        id: 1,
        fkProduct: 1,
        byName: "María Gómez",
        byEmail: "maria.gomez@example.com",
        text: "Muy cómodo y perfecto para entrenar sin molestias.",
        date: "2025-01-19T16:52:30.123Z",
      },
      {
        id: 2,
        fkProduct: 1,
        byName: "Carlos Pérez",
        byEmail: "carlos.perez@example.com",
        text: "Me encanta, ideal para mis sesiones en el gimnasio.",
        date: "2025-01-19T16:53:45.456Z",
      },
      {
        id: 3,
        fkProduct: 2,
        byName: "Laura Fernández",
        byEmail: "laura.fernandez@example.com",
        text: "Este polo es excelente para el uso diario, muy suave.",
        date: "2025-01-19T16:55:12.789Z",
      },
      {
        id: 4,
        fkProduct: 3,
        byName: "Juan Rodríguez",
        byEmail: "juan.rodriguez@example.com",
        text: "Ligero y fresco, ideal para el verano.",
        date: "2025-01-19T16:56:30.234Z",
      },
      {
        id: 5,
        fkProduct: 3,
        byName: "Ana Martínez",
        byEmail: "ana.martinez@example.com",
        text: "Muy cómodo, perfecto para los días más calurosos.",
        date: "2025-01-19T16:58:15.567Z",
      },
      {
        id: 6,
        fkProduct: 4,
        byName: "Pedro Ramírez",
        byEmail: "pedro.ramirez@example.com",
        text: "Un básico imprescindible, lo uso para cualquier ocasión.",
        date: "2025-01-19T16:59:48.890Z",
      },
      {
        id: 7,
        fkProduct: 5,
        byName: "Lucía Torres",
        byEmail: "lucia.torres@example.com",
        text: "Me encanta el estampado, es muy moderno.",
        date: "2025-01-19T17:01:05.123Z",
      },
      {
        id: 8,
        fkProduct: 6,
        byName: "Andrés García",
        byEmail: "andres.garcia@example.com",
        text: "Es perfecto para los días soleados, muy ligero.",
        date: "2025-01-19T17:02:45.456Z",
      },
      {
        id: 9,
        fkProduct: 6,
        byName: "Sofía López",
        byEmail: "sofia.lopez@example.com",
        text: "Ligero y cómodo, me encantó para el verano.",
        date: "2025-01-19T17:04:30.789Z",
      },
      {
        id: 10,
        fkProduct: 7,
        byName: "Elena López",
        byEmail: "elena.lopez@example.com",
        text: "Perfecto para el clima frío, muy cálido y elegante.",
        date: "2025-01-19T17:05:30.123Z",
      },
      {
        id: 11,
        fkProduct: 7,
        byName: "Ricardo Martínez",
        byEmail: "ricardo.martinez@example.com",
        text: "Excelente abrigo, lo uso todo el tiempo en invierno.",
        date: "2025-01-19T17:06:45.456Z",
      },
      {
        id: 12,
        fkProduct: 8,
        byName: "Paula Sánchez",
        byEmail: "paula.sanchez@example.com",
        text: "Muy abrigado, ideal para los días más fríos del invierno.",
        date: "2025-01-19T17:07:30.789Z",
      },
      {
        id: 13,
        fkProduct: 8,
        byName: "Luis Gómez",
        byEmail: "luis.gomez@example.com",
        text: "Me encanta el forro polar, mantiene el calor todo el día.",
        date: "2025-01-19T17:08:12.234Z",
      },
      {
        id: 14,
        fkProduct: 9,
        byName: "Marta Rodríguez",
        byEmail: "marta.rodriguez@example.com",
        text: "Un abrigo elegante y muy moderno, perfecto para ocasiones especiales.",
        date: "2025-01-19T17:09:05.567Z",
      },
      {
        id: 15,
        fkProduct: 9,
        byName: "Javier Pérez",
        byEmail: "javier.perez@example.com",
        text: "De excelente calidad y con un diseño único, lo recomiendo.",
        date: "2025-01-19T17:10:15.890Z",
      },
      {
        id: 16,
        fkProduct: 10,
        byName: "Isabel Fernández",
        byEmail: "isabel.fernandez@example.com",
        text: "Perfecto para el otoño, se siente suave y cómodo.",
        date: "2025-01-19T17:11:40.123Z",
      },
      {
        id: 17,
        fkProduct: 10,
        byName: "Alejandro Ruiz",
        byEmail: "alejandro.ruiz@example.com",
        text: "Muy buen abrigo de cuero, combina con todo, me encanta.",
        date: "2025-01-19T17:12:55.456Z",
      },
      {
        id: 18,
        fkProduct: 11,
        byName: "Cristina Díaz",
        byEmail: "cristina.diaz@example.com",
        text: "Un abrigo muy cálido y liviano, ideal para los días fríos.",
        date: "2025-01-19T17:13:50.789Z",
      },
      {
        id: 19,
        fkProduct: 11,
        byName: "Fernando Jiménez",
        byEmail: "fernando.jimenez@example.com",
        text: "Increíblemente ligero pero muy efectivo para el frío.",
        date: "2025-01-19T17:15:15.123Z",
      },
      {
        id: 20,
        fkProduct: 12,
        byName: "Valeria Torres",
        byEmail: "valeria.torres@example.com",
        text: "Me encanta el estilo oversize, perfecto para el invierno.",
        date: "2025-01-19T17:16:10.456Z",
      },
      {
        id: 21,
        fkProduct: 12,
        byName: "Carlos Martínez",
        byEmail: "carlos.martinez@example.com",
        text: "Cómodo y con mucho estilo, lo uso para cualquier ocasión.",
        date: "2025-01-19T17:17:05.789Z",
      },
      {
        id: 22,
        fkProduct: 13,
        byName: "Ana Gómez",
        byEmail: "ana.gomez@example.com",
        text: "Una cartera muy bonita y elegante, ideal para resaltar cualquier look.",
        date: "2025-01-19T17:18:00.123Z",
      },
      {
        id: 23,
        fkProduct: 13,
        byName: "Luis García",
        byEmail: "luis.garcia@example.com",
        text: "Me encanta la estética de la cartera, es justo lo que buscaba para mi estilo.",
        date: "2025-01-19T17:19:10.456Z",
      },
      {
        id: 24,
        fkProduct: 14,
        byName: "Carla Torres",
        byEmail: "carla.torres@example.com",
        text: "Una cartera sofisticada y perfecta para ocasiones elegantes.",
        date: "2025-01-19T17:20:15.789Z",
      },
      {
        id: 25,
        fkProduct: 14,
        byName: "Ricardo Ruiz",
        byEmail: "ricardo.ruiz@example.com",
        text: "La calidad es impresionante, la cartera tiene un acabado excelente.",
        date: "2025-01-19T17:21:05.123Z",
      },
      {
        id: 26,
        fkProduct: 15,
        byName: "Elena Martínez",
        byEmail: "elena.martinez@example.com",
        text: "Este collar es precioso, el diseño de corazón es muy delicado.",
        date: "2025-01-19T17:22:10.456Z",
      },
      {
        id: 27,
        fkProduct: 15,
        byName: "José López",
        byEmail: "jose.lopez@example.com",
        text: "Me encanta cómo brilla el collar, realmente parece de alta gama.",
        date: "2025-01-19T17:23:15.789Z",
      },
      {
        id: 28,
        fkProduct: 16,
        byName: "Patricia Sánchez",
        byEmail: "patricia.sanchez@example.com",
        text: "los aretes muy bonitos, siempre me los pongo",
        date: "2025-01-19T17:24:05.123Z",
      },
      {
        id: 29,
        fkProduct: 16,
        byName: "Carlos Pérez",
        byEmail: "carlos.perez@example.com",
        text: "Excelente calidad, lo llevo usando varios meses",
        date: "2025-01-19T17:25:20.456Z",
      },
      {
        id: 30,
        fkProduct: 17,
        byName: "Lucía Fernández",
        byEmail: "lucia.fernandez@example.com",
        text: "el audio es perfecto, se escucha genial",
        date: "2025-01-19T17:26:00.789Z",
      },
      {
        id: 31,
        fkProduct: 17,
        byName: "Juan Rodríguez",
        byEmail: "juan.rodriguez@example.com",
        text: "me encanta la calidad del audio",
        date: "2025-01-19T17:27:10.123Z",
      },
      {
        id: 32,
        fkProduct: 18,
        byName: "Isabel Gómez",
        byEmail: "isabel.gomez@example.com",
        text: "super practicos para conectar a tu celular",
        date: "2025-01-19T17:28:00.456Z",
      },
      {
        id: 33,
        fkProduct: 18,
        byName: "Antonio Martínez",
        byEmail: "antonio.martinez@example.com",
        text: "faciles de usar y tienen buen audio",
        date: "2025-01-19T17:29:05.789Z",
      },
      {
        id: 34,
        fkProduct: 1,
        byName: "Daniela Ruiz",
        byEmail: "daniela.ruiz@example.com",
        text: "Excelente producto, me ayuda mucho en mis entrenamientos.",
        date: "2025-01-19T17:30:15.123Z"
      },
      {
        id: 35,
        fkProduct: 2,
        byName: "Pedro Gómez",
        byEmail: "pedro.gomez@example.com",
        text: "Muy cómodo, ideal para el día a día.",
        date: "2025-01-19T17:31:00.456Z"
      },
      {
        id: 36,
        fkProduct: 3,
        byName: "Carlos Sánchez",
        byEmail: "carlos.sanchez@example.com",
        text: "El mejor polo que he comprado, super suave y cómodo.",
        date: "2025-01-19T17:32:05.789Z"
      },
      {
        id: 37,
        fkProduct: 4,
        byName: "Sofía Ramírez",
        byEmail: "sofia.ramirez@example.com",
        text: "Muy fresquito, lo uso para mis paseos en verano.",
        date: "2025-01-19T17:33:15.123Z"
      },
      {
        id: 38,
        fkProduct: 5,
        byName: "Laura Rodríguez",
        byEmail: "laura.rodriguez@example.com",
        text: "Perfecto para los días calurosos, muy cómodo.",
        date: "2025-01-19T17:34:05.456Z"
      },
      {
        id: 39,
        fkProduct: 6,
        byName: "José Martínez",
        byEmail: "jose.martinez@example.com",
        text: "Muy práctico para los días soleados, me encanta.",
        date: "2025-01-19T17:35:20.789Z"
      },
      {
        id: 40,
        fkProduct: 7,
        byName: "Marcela Torres",
        byEmail: "marcela.torres@example.com",
        text: "El estampado es increíble, perfecto para este verano.",
        date: "2025-01-19T17:36:15.123Z"
      },
      {
        id: 41,
        fkProduct: 8,
        byName: "Ricardo González",
        byEmail: "ricardo.gonzalez@example.com",
        text: "Es muy ligero y cómodo, ideal para el calor.",
        date: "2025-01-19T17:37:10.456Z"
      },
      {
        id: 42,
        fkProduct: 9,
        byName: "Mónica López",
        byEmail: "monica.lopez@example.com",
        text: "Lo uso todo el tiempo, perfecto para el frío.",
        date: "2025-01-19T17:38:00.123Z"
      },
      {
        id: 43,
        fkProduct: 10,
        byName: "Juan Pérez",
        byEmail: "juan.perez@example.com",
        text: "Excelente abrigo, me mantiene abrigado todo el día.",
        date: "2025-01-19T17:39:10.789Z"
      },
      {
        id: 44,
        fkProduct: 11,
        byName: "Lucía Fernández",
        byEmail: "lucia.fernandez@example.com",
        text: "Muy ligero pero mantiene el calor, lo uso constantemente.",
        date: "2025-01-19T17:40:05.123Z"
      },
      {
        id: 45,
        fkProduct: 12,
        byName: "Carlos Herrera",
        byEmail: "carlos.herrera@example.com",
        text: "Muy elegante, perfecto para las noches frías.",
        date: "2025-01-19T17:41:20.456Z"
      },
      {
        id: 46,
        fkProduct: 13,
        byName: "Patricia García",
        byEmail: "patricia.garcia@example.com",
        text: "Una cartera increíble, muy bonita y práctica.",
        date: "2025-01-19T17:42:05.789Z"
      },
      {
        id: 47,
        fkProduct: 14,
        byName: "Eva Sánchez",
        byEmail: "eva.sanchez@example.com",
        text: "Es perfecta para ocasiones formales, me encanta.",
        date: "2025-01-19T17:43:15.123Z"
      },
      {
        id: 48,
        fkProduct: 15,
        byName: "Ana Pérez",
        byEmail: "ana.perez@example.com",
        text: "Es un collar precioso, me encanta su brillo.",
        date: "2025-01-19T17:44:05.456Z"
      },
      {
        id: 49,
        fkProduct: 16,
        byName: "Carlos Ruiz",
        byEmail: "carlos.ruiz@example.com",
        text: "Los aretes son muy bonitos, me encantan.",
        date: "2025-01-19T17:45:15.789Z"
      },
      {
        id: 50,
        fkProduct: 17,
        byName: "Laura García",
        byEmail: "laura.garcia@example.com",
        text: "El audio es de excelente calidad, me encanta.",
        date: "2025-01-19T17:46:20.123Z"
      },
      {
        id: 51,
        fkProduct: 18,
        byName: "Fernando López",
        byEmail: "fernando.lopez@example.com",
        text: "Los auriculares son muy cómodos y el sonido es claro.",
        date: "2025-01-19T17:47:05.456Z"
      }
]