import { product } from "../models";

export   const productsDB :product[] =  [ {
    id: 1,
    name: 'Polo Deportivo',
    images: ['/polos/polo1.1.png', '/polos/polo1.2.png', '/polos/polo1.3.png'],
    description: 'Estilo ajustado y ligero, diseñado con tela transpirable y suave para garantizar comodidad al hacer ejercicio. Ideal para actividades deportivas gracias a su ajuste ergonómico y materiales resistentes que ofrecen gran durabilidad. Perfecto para quienes buscan un look atlético con funcionalidad y estilo.',
    category: 'polos',
    price: 43,
    stock: 8,
  },
  {
    id: 2,
    name: 'Polo Casual',
    images: ['/polos/polo2.1.png', '/polos/polo2.2.png', '/polos/polo2.3.png'],
    description: 'Polo de estilo casual confeccionado con algodón de alta calidad para un uso diario cómodo. Su diseño versátil lo hace ideal para combinar con diferentes estilos, mientras que su tela ligera garantiza frescura durante todo el día. Perfecto para quienes buscan comodidad y un look relajado.',
    category: 'polos',
    price: 50,
    stock: 7,
  },
  {
    id: 3,
    name: 'Polo de Manga Corta',
    images: ['/polos/polo3.1.webp', '/polos/polo3.2.jpg', '/polos/polo3.3.jpg'],
    description: 'Diseño fresco y ligero, ideal para días calurosos. Confeccionado con materiales suaves que ofrecen transpirabilidad y comodidad. Este polo de manga corta es perfecto para quienes buscan un look relajado y funcional sin comprometer el estilo.',
    category: 'polos',
    price: 37,
    stock: 9,
  },
  {
    id: 4,
    name: 'Polo Básico',
    images: ['/polos/polo4.1.jpg', '/polos/polo4.2.jpg', '/polos/polo4.3.jpg'],
    description: 'Un polo clásico que combina versatilidad y comodidad. Fabricado con materiales de alta calidad para garantizar durabilidad, este polo básico es una opción confiable para cualquier ocasión. Su diseño minimalista lo convierte en un esencial del armario.',
    category: 'polos',
    price: 30,
    stock: 8,
  },
  {
    id: 5,
    name: 'Polo Estampado',
    images: ['/polos/polo5.1.jpg', '/polos/polo5.2.jpg', '/polos/polo5.3.jpg'],
    description: 'Polo moderno con estampados únicos que destacan en cualquier ocasión. Su diseño combina estilo y comodidad gracias a materiales suaves y transpirables. Ideal para quienes buscan expresar su personalidad con un look original y atractivo.',
    category: 'polos',
    price: 45,
    stock: 7,
  },
  {
    id: 6,
    name: 'Polo de Verano',
    images: ['/polos/polo6.1.webp', '/polos/polo6.2.jpg', '/polos/polo6.3.jpg'],
    description: 'Polo diseñado especialmente para el verano, confeccionado con tela ligera y transpirable para garantizar frescura en días soleados. Su diseño versátil y cómodo lo convierte en la elección perfecta para disfrutar del sol con estilo y comodidad.',
    category: 'polos',
    price: 35,
    stock: 9,
  },

  // Abrigos
  {
    id: 7,
    name: 'Abrigo de Lana',
    images: ['/abrigos/abrigo1.1.jpg', '/abrigos/abrigo1.2.jpg', '/abrigos/abrigo1.3.jpg'],
    description: 'Abrigo grueso de lana para climas fríos.',
    category: 'abrigos',
    price: 120,
    stock: 8,
  },
  {
    id: 8,
    name: 'Abrigo de Invierno',
    images: ['/abrigos/abrigo2.1.png', '/abrigos/abrigo2.2.png', '/abrigos/abrigo2.3.png'],
    description: 'Abrigo de invierno con forro polar.',
    category: 'abrigos',
    price: 150,
    stock: 9,
  },
  {
    id: 9,
    name: 'Abrigo Trench',
    images: ['/abrigos/abrigo3.1.png', '/abrigos/abrigo3.2.png', '/abrigos/abrigo3.3.png'],
    description: 'Abrigo de estilo trench, elegante y moderno.',
    category: 'abrigos',
    price: 170,
    stock: 7,
  },
  {
    id: 10,
    name: 'Abrigo de Cuero',
    images: ['/abrigos/abrigo4.1.png', '/abrigos/abrigo4.2.png', '/abrigos/abrigo4.3.png'],
    description: 'Abrigo de cuero, ideal para el otoño.',
    category: 'abrigos',
    price: 200,
    stock: 8,
  },
  {
    id: 11,
    name: 'Abrigo de Plumas',
    images: ['/abrigos/abrigo5.1.png', '/abrigos/abrigo5.2.png', '/abrigos/abrigo5.3.png'],
    description: 'Abrigo ligero pero cálido, perfecto para el frío.',
    category: 'abrigos',
    price: 140,
    stock: 9,
  },
  {
    id: 12,
    name: 'Abrigo Oversized',
    images: ['/abrigos/abrigo6.1.jpg', '/abrigos/abrigo6.2.jpg', '/abrigos/abrigo6.3.jpg'],
    description: 'Abrigo de estilo oversize para un look relajado.',
    category: 'abrigos',
    price: 160,
    stock: 7,
  },

  // Accesorios
  {
    id: 13,
    name: 'Cartera Estética',
    images: ['/accesorios/accesorio1.1.webp', '/accesorios/accesorio1.2.jpg', '/accesorios/accesorio1.3.jpg'],
    description: 'Cartera estética para mayor resplandor.',
    category: 'accesorios',
    price: 80,
    stock: 8,
  },
  {
    id: 14,
    name: 'Cartera Elegante',
    images: ['/accesorios/accesorio2.1.webp', '/accesorios/accesorio2.2.jpg', '/accesorios/accesorio2.3.jpg'],
    description: 'Cartera blanca para ocasiones elegantes.',
    category: 'accesorios',
    price: 100,
    stock: 7,
  },
  {
    id: 15,
    name: 'Collar de Corazón',
    images: ['/accesorios/accesorio3.1.webp', '/accesorios/accesorio3.2.jpg', '/accesorios/accesorio3.3.jpg'],
    description: 'Collar de corazón de metal bañado en oro.',
    category: 'accesorios',
    price: 60,
    stock: 9,
  },
  {
    id: 16,
    name: 'Bufanda de Lana',
    images: ['/accesorios/accesorio4.1.webp', '/accesorios/accesorio4.2.jpg', '/accesorios/accesorio4.3.jpg'],
    description: 'Bufanda cálida de lana para el invierno.',
    category: 'accesorios',
    price: 40,
    stock: 8,
  },
  {
    id: 17,
    name: 'Sombrero de Paja',
    images: ['/accesorios/accesorio5.1.webp', '/accesorios/acessorio5.2.jpg', '/accesorios/accesorio5.3.jpg'],
    description: 'Sombrero ligero para los días de verano.',
    category: 'accesorios',
    price: 35,
    stock: 7,
  },
  {
    id: 18,
    name: 'Guantes de Cuero',
    images: ['/accesorios/accesorio6.1.webp', '/accesorios/accesorio6.2.jpg', '/accesorios/accesorio6.3.jpg'],
    description: 'Guantes de cuero suaves y cálidos.',
    category: 'accesorios',
    price: 50,
    stock: 9,
  }
]